resources:
  - name: application
    type: git
    source:
      uri: https://github.com/MarcialRosales/dot-net-pcf-workshop
      branch: master
      paths:
        - WebFormsApp

jobs:
- name: discover
  public: true
  plan:
  - task: find-msbuild
    config:
      platform: windows
      run:
        path: powershell
        args:
        - dir '/Program Files'
#        - dir /Windows/Microsoft.NET/Framework64/v4.0.30319
- name: unit-test
  public: true
  plan:
  - get: application
    trigger: true
  - task: build-and-test
    config:
      platform: windows
      run:
        path: powershell
        args:
        - ../build.ps1
        dir: a/WebFormsApp/WebFormsApp
      inputs:
      - name: application
        path: a

- name: publish
  public: true
  plan:
  - get: application
    passed:
    - unit-test
    trigger: true

  - task: build-and-publish
    config:
      platform: windows
      run:
        path: powershell
        args:
        - ./build.ps1
        - -mode publish
        dir: application/WebFormsApp
      inputs:
      - name: application
#        path: ""
      outputs:
      - name: publish
#        path: ""
#  - put: pcf
#    params:
#      manifest: pipeline/dev/manifest.yml
#      path: publish/Pivotal.Security.Entitlements
